package com.maislimpo.maislimpo.view;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;
import com.maislimpo.maislimpo.controller.UsuarioController;

@Component
public class TelaLogin extends javax.swing.JFrame {
	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form TelaLogin
	 */

	private ApplicationContext applicationContext;
	private UsuarioController usuarioController;

	@Autowired
	public TelaLogin(UsuarioController usuarioController, ApplicationContext applicationContext) {
		this.usuarioController = usuarioController;
		this.applicationContext = applicationContext;
		initComponents();
		configureFrame();
	}

	private void configureFrame() {
		setSize(420, 420);
		setResizable(false);
		setLocationRelativeTo(null); // Centraliza
		getContentPane().setBackground(Color.WHITE);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // garante que a aplicação feche
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		IconLogin = new javax.swing.JLabel();
		Titulo = new javax.swing.JLabel();
		Email = new javax.swing.JLabel();
		Senha = new javax.swing.JLabel();
		textEmail = new javax.swing.JTextField();
		textSenha = new javax.swing.JPasswordField();
		botaoEntrar = new javax.swing.JButton();
		botaoCadastro = new javax.swing.JButton();
		textCadastro = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Projeto Mais Limpo - Login");
		setBackground(new java.awt.Color(255, 255, 255));
		setResizable(false);

		IconLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		IconLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadeadoAzul136.png"))); // NOI18N
		IconLogin.setVerticalAlignment(javax.swing.SwingConstants.TOP);

		Titulo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
		Titulo.setForeground(new java.awt.Color(51, 153, 255));
		Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Titulo.setText("Bem Vindo ao Projeto +Limpo!");

		Email.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
		Email.setForeground(new java.awt.Color(51, 153, 255));
		Email.setText("E-mail");

		Senha.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
		Senha.setForeground(new java.awt.Color(51, 153, 255));
		Senha.setText("Senha");

		textEmail.setBackground(new java.awt.Color(102, 204, 255));
		textEmail.setForeground(new java.awt.Color(0, 0, 0));
		textEmail.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				textEmailActionPerformed(evt);
			}
		});

		textSenha.setBackground(new java.awt.Color(102, 204, 255));
		textSenha.setForeground(new java.awt.Color(0, 0, 0));
		textSenha.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				textSenhaActionPerformed(evt);
			}
		});

		botaoEntrar.setBackground(new java.awt.Color(102, 204, 255));
		botaoEntrar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
		botaoEntrar.setForeground(new java.awt.Color(0, 0, 255));
		botaoEntrar.setText("ENTRAR");
		botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoEntrarActionPerformed(evt);
			}
		});

		botaoCadastro.setBackground(new java.awt.Color(102, 204, 255));
		botaoCadastro.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
		botaoCadastro.setForeground(new java.awt.Color(0, 0, 255));
		botaoCadastro.setText("CADASTRO");
		botaoCadastro.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoCadastroActionPerformed(evt);
			}
		});

		textCadastro.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
		textCadastro.setForeground(new java.awt.Color(51, 153, 255));
		textCadastro.setText("Não possui um login? Cadastre-se! →");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(IconLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup().addGap(60, 60, 60).addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(Email, javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(Senha, javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup().addComponent(textCadastro).addGap(18, 18, 18)
										.addComponent(botaoCadastro))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(textSenha, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
										.addComponent(textEmail, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(botaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(62, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(16, 16, 16).addComponent(Titulo)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(IconLogin)
						.addGap(0, 0, 0).addComponent(Email).addGap(5, 5, 5)
						.addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(Senha)
						.addGap(5, 5, 5)
						.addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(botaoEntrar)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(botaoCadastro).addComponent(textCadastro))
						.addContainerGap(107, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoEntrarActionPerformed

		String email = textEmail.getText();
		String senha = new String(textSenha.getPassword());

		if (email.isEmpty() || senha.isEmpty()) {
			JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
			return; // Interrompe aqui se estiver vazio
		}

		try {
			if (usuarioController.loginUsuario(email, senha)) {
				// Login correto → abre TelaPrincipal
				// Se TelaPrincipal também for um @Component gerenciado pelo Spring:
				// TelaPrincipal telaPrincipal = context.getBean(TelaPrincipal.class);
				// Ou injetar via construtor se ela precisar de dependências.
				// Por simplicidade, vamos instanciar diretamente aqui,
				// mas idealmente ela também seria um bean ou receberia dependências.
				TelaPrincipal telaPrincipal = new TelaPrincipal(); // Assumindo que ela pode ser instanciada assim por
																	// agora
				telaPrincipal.setVisible(true);
				this.dispose(); // Fecha a tela de login
			} else {
				JOptionPane.showMessageDialog(this, "Email ou senha inválidos.", "Falha no Login",
						JOptionPane.ERROR_MESSAGE);
			}
		} catch (Exception e) {
			// Captura exceções mais genéricas que podem vir do service/controller
			JOptionPane.showMessageDialog(this, "Ocorreu um erro ao tentar fazer login: " + e.getMessage(), "Erro",
					JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_botaoEntrarActionPerformed

	private void botaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoCadastroActionPerformed

		TelaCadastro telaCadastro = applicationContext.getBean(TelaCadastro.class);
		telaCadastro.setVisible(true);
		this.dispose();

	}// GEN-LAST:event_botaoCadastroActionPerformed

	private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textEmailActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_textEmailActionPerformed

	private void textSenhaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textSenhaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_textSenhaActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel Email;
	private javax.swing.JLabel IconLogin;
	private javax.swing.JLabel Senha;
	private javax.swing.JLabel Titulo;
	private javax.swing.JButton botaoCadastro;
	private javax.swing.JButton botaoEntrar;
	private javax.swing.JLabel textCadastro;
	private javax.swing.JTextField textEmail;
	private javax.swing.JPasswordField textSenha;
	// End of variables declaration//GEN-END:variables
}
